version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "python manage.py wait_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres
    environment:
      - POSTGRES_DB=microservicedrf
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - 5432:5432